# Generated by Django 4.1.2 on 2023-01-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(default='Bez Grupy', max_length=30),
            preserve_default=False,
        ),
    ]
