# Generated by Django 4.1.2 on 2023-01-22 18:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_group_group_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('group_name', 'user')},
        ),
    ]
