# Generated by Django 4.1.2 on 2023-02-05 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_shift_employee_alter_shift_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='employee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shift',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.group'),
            preserve_default=False,
        ),
    ]
