# Generated by Django 4.1.2 on 2023-02-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_shift_employee_alter_shift_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
