# Generated by Django 4.1.2 on 2023-02-11 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_constraints_avaibleconstraints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaibleconstraints',
            old_name='representation',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='avaibleconstraints',
            name='constraints',
        ),
        migrations.RemoveField(
            model_name='constraints',
            name='group',
        ),
        migrations.AddField(
            model_name='constraints',
            name='avaible_constraints',
            field=models.ManyToManyField(blank=True, to='main.avaibleconstraints'),
        ),
        migrations.AddField(
            model_name='group',
            name='constraints',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.constraints'),
        ),
    ]
