# Generated by Django 4.1.2 on 2023-02-11 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_representation_avaibleconstraints_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaibleconstraints',
            name='description',
            field=models.TextField(default='elo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avaibleconstraints',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='constraints',
            name='representation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='group',
            name='constraints',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.constraints'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=50),
        ),
    ]
