# Generated by Django 4.1.2 on 2023-02-12 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_avaibleconstraints_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaibleconstraints',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='constraints',
            unique_together={('representation', 'user')},
        ),
    ]
