# Generated by Django 4.1.2 on 2023-02-20 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_avaibleconstraints_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvaibleConstraints',
            new_name='AvailableConstraints',
        ),
        migrations.RenameField(
            model_name='constraints',
            old_name='avaible_constraints',
            new_name='available_constraints',
        ),
    ]
